
trigger:
- Studio_2026

variables:
- name: StudioProductIdentifier
  value: 'Studio19'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- group: StudioCommunityToolkitVersions

name: $(BuildDefinitionName).$(SourceBranchName)_$(Version.Major).$(Version.Minor).$(Version.Patch).$(Build.BuildId)
#- group: 'SDLPLC Authenticode Credentials'

resources:
  pipelines:
  - pipeline: TradosStudio_Resource
    project: TradosStudio
    source: TradosStudio

stages:
- stage: Build
  displayName: 'Build Studio Community Toolkit'
  jobs:
  - job: Do_Build
    displayName: 'Do build'
    pool:
      vmImage: 'windows-latest'
    steps:
 


    
    - task: NuGetToolInstaller@0
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '3d68cc84-2fee-45a5-9a2c-27d1429712fc'
        definition: '1258'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/Release/19.0.0'
        allowFailedBuilds: false
        artifactName: 'binaries'
        path: '$(ProgramFiles)\Trados\Trados Studio\$(StudioProductIdentifier)'

    - task: NuGetCommand@2
      displayName: "Restore Trados Community Toolkit.sln"
      inputs:
        restoreSolution: '.\Trados Community Toolkit.sln'

    - task: SDLVersion@2
      displayName: 'Version Assemblies'
      inputs:
        FilenamePattern: 'AssemblyInfo.cs'
        Field: AssemblyFileVersion
        VersionNumber: '$(BuildDefinitionName)_$(Version.Major).$(Version.Minor).$(Version.Patch).0'

    - task: VSBuild@1
      inputs:
        solution: '.\Trados Community Toolkit.sln'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)' 

    - task: VersionNuspec@2
      displayName: 'Version Nuspec'
      inputs:
        VersionNumber: '$(Version.Major).$(Version.Minor).$(Version.Patch).0'
        VersionRegex: '\d+\.\d+\.\d+\.\d+'

    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
       command: pack
       packagesToPack: .\*.nuspec
       packDestination: '$(Build.ArtifactStagingDirectory)\packages'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\packages'
        ArtifactName: 'studio-toolkit-drop'
        publishLocation: 'Container'

- stage: Publish_Beta
  displayName: 'Publish beta version on private feed'
  jobs:
  - deployment: Publish_Beta
    displayName: 'Publish on azure internal devops feed'
    pool:
      vmImage: 'windows-latest'
    environment: 'Azure DevOps feed'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Agent.BuildDirectory)/**/*.nupkg;!$(Agent.BuildDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: 'af66e256-9c46-4fba-ad75-09bf110ec1cc'
              allowPackageConflicts: true

- stage: Publish_Nuget
  displayName: 'Publish nuget packages'
  jobs:
  - deployment: Publish_Nuget
    displayName: 'Publish on azure external devops feed'
    pool:
      vmImage: 'windows-latest'
    environment: 'Azure DevOps feed'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Agent.BuildDirectory)/**/*.nupkg;!$(Agent.BuildDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'Nuget'
              allowPackageConflicts: true
