// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Sdl Studio Community Toolkit")]
[assembly: AssemblyVersionAttribute("0.9")]
[assembly: AssemblyFileVersionAttribute("0.9")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Sdl Studio Community Toolkit";
        internal const System.String AssemblyVersion = "0.9";
        internal const System.String AssemblyFileVersion = "0.9";
        internal const System.Boolean ComVisible = false;
    }
}
